services:

  game_night_app:
    build: .
    container_name: game_night_app
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
      - FLASK_DEBUG
      - SECRET_KEY
      - DATABASE_URL
      - PGHOST
      - PGPORT
      - MAIL_SERVER
      - MAIL_PORT
      - MAIL_USE_TLS
      - MAIL_USE_SSL
      - MAIL_USERNAME
      - MAIL_PASSWORD
      - MAIL_DEFAULT_SENDER
      - FLASK_APP
    restart: always
    healthcheck:
      test: ["CMD", "python", "-c", "import urllib.request; urllib.request.urlopen('http://localhost:8000/')"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 15s
    networks:
      - web_network
    labels:
      - "traefik.enable=true"

      # Router for game night app
      - "traefik.http.routers.game_night.rule=Host(`gamenight.sgammill.com`)"
      - "traefik.http.routers.game_night.entrypoints=websecure"
      - "traefik.http.routers.game_night.tls.certresolver=cloudflare"

      # Service config
      - "traefik.http.services.game_night.loadbalancer.server.port=8000"

networks:
  web_network:
    external: true